name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute test1 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/CourseRunTest.php
      continue-on-error: true

    - name: Execute test2 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/CourseTest.php
      continue-on-error: true

    - name: Execute test3 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/EmployeeTest.php
      continue-on-error: true
    
    - name: Execute test4 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/EngineerTest.php
      continue-on-error: true

    - name: Execute test5 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/ForumTest.php
      continue-on-error: true

    - name: Execute test6 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/HRTest.php
      continue-on-error: true

    - name: Execute test7 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/LearnerTest.php
      continue-on-error: true

    - name: Execute test8 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/MessageTest.php
      continue-on-error: true

    - name: Execute test9 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/PostTest.php
      continue-on-error: true

    - name: Execute test10 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/QualificationTest.php
      continue-on-error: true

    - name: Execute test11 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/SectionTest.php
      continue-on-error: true

    - name: Execute test12 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/TrainerTest.php
      continue-on-error: true

    - name: Execute test13 (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/QuizTest.php
      continue-on-error: true
