name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute Course Run test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/CourseRunTest.php
      continue-on-error: true

    - name: Execute Course test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/CourseTest.php
      continue-on-error: true

    - name: Execute Employee test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/EmployeeTest.php
      continue-on-error: true
    
    - name: Execute Engineer test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/EngineerTest.php
      continue-on-error: true

    - name: Execute Forum test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/ForumTest.php
      continue-on-error: true

    - name: Execute HR test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/HRTest.php
      continue-on-error: true

    - name: Execute Learner test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/LearnerTest.php
      continue-on-error: true

    - name: Execute Message test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/MessageTest.php
      continue-on-error: true

    - name: Execute Post test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/PostTest.php
      continue-on-error: true

    - name: Execute Qualification test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/QualificationTest.php
      continue-on-error: true

    - name: Execute Section test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/SectionTest.php
      continue-on-error: true

    - name: Execute Trainer test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/TrainerTest.php
      continue-on-error: true

    - name: Execute Quiz test (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php vendor/bin/phpunit Testing/QuizTest.php
      continue-on-error: true
